[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
KaHyPar = "2a6221f6-aa48-11e9-3542-2d9e0ef01880"
Plasmo = "d3f7391f-f14a-50cc-bbe4-76a32d1bad3c"
PlasmoPlots = "a21664a3-f668-4e98-8a13-7892286ec16a"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Documenter = "~0.25"
